name: 'secop'
version: '1.0.0'
config-version: 2

profile: 'secop'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  dataset_bq: artful-sled-419501.secop
  normalize_function: '`artful-sled-419501`.secop.normalize_text'
  macro_path: 'macros/'

     
models:
  secop:
    bigquery:
      tags: [bigquery]
      aux_tables:
        materialized: table
        tags: [aux_tables]
      dimensions:
        materialized: table
        tags: [dimensions]
      facts:
        materialized: table
        tags: [facts]
      trans_views:
        materialized: view
        tags: [views]

