name: 'finkargo'
version: '1.0.0'
config-version: 2

profile: 'duckdb_fk'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  namespace_dns: 6ba7b810-9dad-11d1-80b4-00c04fd430c8
  execution_date: "2024-01-01"
  macro_path: 'macros/'

on-run-start:
    - '{{create_udfs()}}'
      
models:
  finkargo:
    duckdb:
      tags: [duckdb]
      aux_tables:
        materialized: table
        tags: [aux_tables]
      dimensions:
        materialized: table
        post_hook: "{{ export_to_parquet(this.table) }}"
        tags: [aux_tables]

