{% macro clean_providers() %}
CREATE OR REPLACE FUNCTION main.clean_providers(string) AS 
    REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
        REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
        UPPER(string), '-', ' '), ',', ' '), '.', ' '), '/', ''), '#', ' '), '|', ' '), '¿', ''), '?', ''), ';', ''), '&', ''), '%', ''), ':', ' '), '´', ''), '`', ''), '''', ''), '(', ''), ')', ''), '¡', ''), '!', ''), '[', ' '), ']', ' '), '    ', ' '), '   ', ' '), '  ', ' '), 'COLIMITED', 'CO LIMITED'), 'COLTD', 'CO LTD'), 'IMP&EXP', 'IMP & EXP'), ' Y ', ' AND '), ' & ', ' AND '), ' LIMITED', ' LTD'), ' COP', ' CORP'), ' S A', ' SA'),
        'CARPIGIANI GROUP-ALI GROUP SR!', 'CARPIGIANI GROUP-ALI GROUP SRL'),
        'ANHUI TAICHENG PAPER&PLASTIC TECHNOLOGY CO LTD', 'ANHUI TAICHENG PAPER AND PLASTIC TECHNOLOGY CO LTD'),
        'ARCELOR MITTAL INTERNATIONAL LUXEMBURGO', 'ARCELORMITTAL INTERNATIONAL LUXEMBOURG SA'),
        'ARCELOR MITTAL INTERNATIONAL LUXEMBURGO SA', 'ARCELORMITTAL INTERNATIONAL LUXEMBOURG SA'),
        'INGERSOLL RAND INDUSTRIAL IRELAND LIMITED', 'INGERSOLL RAND INDUSTRIAL IRELAND LTD'),
        'INGERSOLL-RAND INDUSTRIAL IRELAND LIMITED', 'INGERSOLL RAND INDUSTRIAL IRELAND LTD'),
        'INGERSOLL-RAND INDUSTRIAL IRELAND LTD', 'INGERSOLL RAND INDUSTRIAL IRELAND LTD'),
        'AUTOMOTIVE DRIVELINE SISTEMS LTD', 'AUTOMOTIVE DRIVELINE SYSTEMS LTD'),
        'FERROMAC INTERNATIONAL', 'FERROMAC INTERNATIONAL NV'),
        'GGTEX SA', 'GG TEX SA'),
        'GPI INTERNACIONAL INC', 'GPI INTERNATIONAL INC'),
        'GUANGDONG WORLD OPTO-ELECTRONICCO LTD', 'GUANGDONG WORLD OPTO-ELECTRONIC CO LTD'),
        'HAINING ZHUNAGHENG PLASTIC INDUSTRY CO LTD', 'HAINING ZHUANGHENG PLASTIC INDUSTRY CO LTD'),
        'LINKING GLOBAL CORPORATION', 'LINKING GLOBAL CORP'),
        'SHANDONG KAIXUAN RUBBER CO', 'SHANDONG KAIXUAN RUBBER CO LTD'),
        'SUZHOU LAISHENG IMP AND EXP CO', 'SUZHOU LAISHENG IMP AND EXP CO LTD'),
        'ZHAOYANG INTEGRAL SUPPLIES LTD', 'ZHAOYANG INTEGRAL SUPPLIES CHINA LTD')
{% endmacro %}