version: 2

sources:
  - name: secop
    schema: secop  # Dataset en BigQuery
    database: artful-sled-419501   # ID del proyecto en BigQuery
    tables:
      - name: pdf_control        # Nombre de la tabla en BigQuery
      - name: secop            # Nombre de la tabla en BigQuery
